-- Run this script to create all tables in the proper order (MySQL)
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS Clients (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    ClientName VARCHAR(255) NOT NULL,
    CompanyName VARCHAR(255) DEFAULT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Products (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Orders (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    ClientId CHAR(36) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT FK_Orders_Client FOREIGN KEY (ClientId) REFERENCES Clients(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS OrderProducts (
    OrderId CHAR(36) NOT NULL,
    ProductId CHAR(36) NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (OrderId, ProductId),
    CONSTRAINT FK_OrderProducts_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    CONSTRAINT FK_OrderProducts_Product FOREIGN KEY (ProductId) REFERENCES Products(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;

