-- Run this script to create all log tables for models (MySQL)
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS ClientLogs (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    ClientId CHAR(36) NULL,
    OperationType VARCHAR(20) NOT NULL,
    ClientName VARCHAR(255) NOT NULL,
    CompanyName VARCHAR(255) DEFAULT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT NULL,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    LoggedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LoggedBy VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_ClientLogs_Client FOREIGN KEY (ClientId) REFERENCES Clients(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ProductLogs (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    ProductId CHAR(36) NULL,
    OperationType VARCHAR(20) NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT NULL,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    LoggedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LoggedBy VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_ProductLogs_Product FOREIGN KEY (ProductId) REFERENCES Products(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS OrderLogs (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    OrderId CHAR(36) NULL,
    OperationType VARCHAR(20) NOT NULL,
    ClientId CHAR(36) NOT NULL,
    ProductsSnapshot JSON DEFAULT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT NULL,
    IsDeleted TINYINT(1) NOT NULL DEFAULT 0,
    LoggedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LoggedBy VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_OrderLogs_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    CONSTRAINT FK_OrderLogs_Client FOREIGN KEY (ClientId) REFERENCES Clients(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS OrderProductsLogs (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    OrderId CHAR(36) NULL,
    ProductId CHAR(36) NULL,
    OperationType VARCHAR(20) NOT NULL,
    Quantity INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LoggedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LoggedBy VARCHAR(255) DEFAULT NULL,
    CONSTRAINT FK_OrderProductsLogs_OrderProduct FOREIGN KEY (OrderId, ProductId)
        REFERENCES OrderProducts(OrderId, ProductId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS=1;
